name: CI
run-name: Ejecución de Pipeline de CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: reset database
        run: npm run reset-db  

      - name: Run tests
        run: npm test